---
deployment:
    tasks:
        - export DEPLOYPATH1=//home4/skoolfdp/public_html/FamilyFinance/application/
        - export DEPLOYPATH2=//home4/skoolfdp/public_html/FamilyFinance/assets/css/
        - /bin/cp -R  application/controllers $DEPLOYPATH1
        - /bin/cp -R  application/models $DEPLOYPATH1
        - /bin/cp -R  application/views $DEPLOYPATH1
        - /bin/cp -R  assets/css/styles.css $DEPLOYPATH2
